title: "Alex Atanassov"
description: "Robotics + ML Portfolio"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# optional
minimal_mistakes_skin: "air"

header_pages:
  - index.md
  - projects.md
  - blog.md
  - about.md
